version: 2

models:
  - name: dim_zones
    description: ""
    columns:
      - name: locationid
        data_type: integer
        description: ""

      - name: borough
        data_type: text
        description: ""

      - name: zone
        data_type: text
        description: ""

      - name: service_zone
        data_type: text
        description: ""

  - name: fact_trips
    description: ""
    columns:
      - name: tripid
        data_type: text
        description: ""

      - name: vendorid
        data_type: integer
        description: ""

      - name: service_type
        data_type: text
        description: ""

      - name: ratecodeid
        data_type: integer
        description: ""

      - name: pickup_locationid
        data_type: integer
        description: ""

      - name: pickup_borough
        data_type: text
        description: ""

      - name: pickup_zone
        data_type: text
        description: ""

      - name: dropoff_locationid
        data_type: integer
        description: ""

      - name: dropoff_borough
        data_type: text
        description: ""

      - name: dropoff_zone
        data_type: text
        description: ""

      - name: pickup_datetime
        data_type: timestamp without time zone
        description: ""

      - name: dropoff_datetime
        data_type: timestamp without time zone
        description: ""

      - name: store_and_fwd_flag
        data_type: text
        description: ""

      - name: passenger_count
        data_type: integer
        description: ""

      - name: trip_distance
        data_type: numeric
        description: ""

      - name: trip_type
        data_type: integer
        description: ""

      - name: fare_amount
        data_type: numeric
        description: ""

      - name: extra
        data_type: numeric
        description: ""

      - name: mta_tax
        data_type: numeric
        description: ""

      - name: tip_amount
        data_type: numeric
        description: ""

      - name: tolls_amount
        data_type: numeric
        description: ""

      - name: improvement_surcharge
        data_type: numeric
        description: ""

      - name: total_amount
        data_type: numeric
        description: ""

      - name: payment_type
        data_type: integer
        description: ""

      - name: payment_type_description
        data_type: text
        description: ""